CREATE TABLE Users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    givenname VARCHAR(30) NOT NULL, 
    surname VARCHAR(30) NOT NULL, 
    email VARCHAR(80) NOT NULL, 
    password BINARY(80) NOT NULL, 
    lastaccess DATETIME
    CONSTRAINT UNIQUE (email)
    );
ALTER TABLE Users AUTO_INCREMENT = 2220;

CREATE TABLE Accounts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userid INT UNSIGNED NOT NULL, 
    name VARCHAR(30) NOT NULL,
    balance DECIMAL(13,2) NOT NULL DEFAULT 0,
    notes VARCHAR(512),
    FOREIGN KEY(userid) REFERENCES Users(id)
    CONSTRAINT UNIQUE (id, userid, name)
);
ALTER TABLE Accounts AUTO_INCREMENT = 102;

CREATE TABLE Bokens (
    token VARBINARY(300) PRIMARY KEY,
    userid INT UNSIGNED NOT NULL,
    expdate DATETIME NOT NULL,
    FOREIGN KEY(userid) REFERENCES Users(id)
);

CREATE TABLE Transactions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    accountid INT UNSIGNED NOT NULL,
    payerid INT UNSIGNED NOT NULL, 
    paiddate DATETIME NOT NULL DEFAULT NOW(), 
    payee VARCHAR(100) NOT NULL,
    amount DECIMAL(13,2) NOT NULL,
    category VARCHAR(255) NOT NULL DEFAULT 'Misc',
    FOREIGN KEY(payerid) REFERENCES Users(id),
    FOREIGN KEY(accountid) REFERENCES Accounts(id)    
);
ALTER TABLE Transactions AUTO_INCREMENT = 31;