CREATE TABLE Users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    givenname VARCHAR(30) NOT NULL, 
    surname VARCHAR(30) NOT NULL, 
    email VARCHAR(50) NOT NULL, 
    password BINARY(128) NOT NULL, 
    spice BINARY(128) NOT NULL,  
    lastaccess DATETIME
    );
ALTER TABLE Users AUTO_INCREMENT = 2220;

CREATE TABLE Transactions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payerid INT UNSIGNED NOT NULL FORIEGN KEY REFERENCES Users(id),
    paiddate DATETIME NOT NULL DEFAULT GETDATE(), 
    payee VARCHAR(100) NOT NULL,
    amount DECIMAL(13,2) NOT NULL,
    category VARCHAR(255) NOT NULL DEFAULT 'Misc'
);