GRANT USAGE ON *.* TO 'gary'@'%' IDENTIFIED BY PASSWORD '*26CF6C0B199517ED06F9C618898D91B3E7ABB3A0'
GRANT USAGE ON *.* TO 'gary'@'localhost' IDENTIFIED BY PASSWORD '*26CF6C0B199517ED06F9C618898D91B3E7ABB3A0'
GRANT SELECT, INSERT, UPDATE, DELETE ON `MobileLedger`.* TO 'gary'@'localhost'                             
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_adduser` TO 'gary'@'localhost'                               
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_login` TO 'gary'@'localhost'                                 
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_addaccount` TO 'gary'@'localhost'                            
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_listaccounts` TO 'gary'@'localhost'
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_getuseremail` TO 'gary'@'localhost'
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_getuserid` TO 'gary'@'localhost'
GRANT USAGE ON *.* TO 'gary'@'192.168.1.124' IDENTIFIED BY PASSWORD '*26CF6C0B199517ED06F9C618898D91B3E7ABB3A0'
GRANT SELECT, INSERT, UPDATE, DELETE ON `MobileLedger`.* TO 'gary'@'192.168.1.124'                             
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_addaccount` TO 'gary'@'192.168.1.124'                            
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_listaccounts` TO 'gary'@'192.168.1.124'                          
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_login` TO 'gary'@'192.168.1.124'                                 
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_adduser` TO 'gary'@'192.168.1.124'
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_getuseremail` TO 'gary'@'192.168.1.124'
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_getuserid` TO 'gary'@'192.168.1.124'
GRANT USAGE ON *.* TO 'gary'@'192.168.1.7' IDENTIFIED BY PASSWORD '*26CF6C0B199517ED06F9C618898D91B3E7ABB3A0'
GRANT SELECT, INSERT, UPDATE, DELETE ON `MobileLedger`.* TO 'gary'@'192.168.1.7'                             
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_addaccount` TO 'gary'@'192.168.1.7'                            
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_listaccounts` TO 'gary'@'192.168.1.7'                          
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_login` TO 'gary'@'192.168.1.7'                                 
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_adduser` TO 'gary'@'192.168.1.7'
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_getuseremail` TO 'gary'@'192.168.1.7'
GRANT EXECUTE ON PROCEDURE `MobileLedger`.`sp_getuserid` TO 'gary'@'192.168.1.7'
